### PR TITLE
[switch_ivr_play_say] Make better use of memory during speed change

### PR DESCRIPTION
**Pull request by yois615**
Relates to #244

### CODE REVIEW

**Comment by yois615** [comment]
@rucc Your PR is awesome and I greatly appreciate your code.  Hopefully we can get this to the finish line
@toraritte

**Comment by toraritte** [comment]
@yois615 Thank you so much for working on this! Just a heads up that I think rucc has permanently moved on from this project so you'll probably have more success in creating a PR from your own repot and referencing rucc's PR.

(For context: I found rucc's PR after it was ignored for a year, but he was using it at his company in production already. I left a note in the PR that this is needed to be fixed, an FS dev asked for changes, and after I reached out to rucc, he kindly agreed to work on it for a couple weeks even though this project was already irrelevant to him. After he was done, there were reviews, but they didn't make much sense to me. This is where another year has passed and you came into the picture:)

**Comment by yois615** [comment]
@toraritte Thanks. It seems you have write access to this repo though, as it shows a force push from you.
If not I'll cherry pick these 3 commits, add mine, squash, rebase, and open a new PR against SignalWire repo.

Do you have C knowledge? I'm thinking and testing that sp_prev doesn't need SWITCH_RECOMMENDED_BUFFER_SIZE, which is 8192 bytes. The audio buffer is 1024, so we're wasting 7k of stack memory this way.

**Comment by rucc** [comment]
Hi @yois615 
I have added you as a collaborator.

Concerning SWITCH_RECOMMENDED_BUFFER_SIZE: I don't have the required FS knowledge to tell what can be the smallest upper limit for audio frame size. So I took a very defensive approach and used heap memory for that, which was replaced with SWITCH_RECOMMENDED_BUFFER_SIZE later following Anthony's suggestion.
And since it was recommended by Anthony, I think this is a good limit.

**Pull request merged**
